# version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: "${APP_NAME}_db"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}_phpmyadmin"
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: "${APP_NAME}_mailpit"
    restart: unless-stopped
    ports:
      - "${MAIL_SERVER_PORT}:${MAIL_SERVER_PORT}"
      - "${MAIL_CLIENT_PORT}:${MAIL_CLIENT_PORT}"

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: "${APP_NAME}_app"
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - db
    env_file:
      - docker/.env.docker
    tty: true
    stdin_open: true

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata:

networks:
  laravel:
    name: ${APP_NAME}
